language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
node_js:
  - '8'
install:
  - yarn global add codecov
  - yarn
script:
  - npm run test:coverage
  - codecov
  - cd example && yarn
  - npm run build
  - cd ../
matrix:
  allow_failures: []
  fast_finish: true
after_success:
  - npm run release
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: example/public
  keep_history: true
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/