language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
node_js:
  - '8'
script:
  - npm run test
  - npm run build
matrix:
  allow_failures: []
  fast_finish: true
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/