language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
node_js:
  - '8'
install:
  - yarn global add codecov
  - yarn
script:
  - npm run test:coverage
  - codecov
matrix:
  allow_failures: []
  fast_finish: true
after_success:
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/