name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:coverage
      - uses: codecov/codecov-action@v5
      - run: mv "$(pnpm pack | tail -n 1)" pkg.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: package-art
          path: pkg.tgz
  test_example:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: package-art
          path: example
      - run: npm install pkg.tgz --only=development --no-package-lock
      - run: npm install
      - run: npm run build -- --prefix-paths
      - if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: example-art
          path: example/public
  deploy_example:
    if: github.event_name == 'push'
    needs: test_example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: example-art
          path: public
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
